language: python
env:
   - TOXENV=py26
   - TOXENV=py27
   - TOXENV=rhel6

install:
   - pip install tox
   - pip install pep8
script:
   - tox

notifications:
    email:
        - taxii-commits-list@lists.mitre.org
